# Site settings
title: norux's Home
mynick: norux
myname: Andrew Heebum Kwak
motto: This is norux's Home.
# description: > # description

email: andrew@norux.me

baseurl: ""
url: "https://norux.github.io"

github_username: norux
blog: http://norux.me

highlighter: pygments


# Build settings
markdown: kramdown
permalink: pretty
